name: Fly Deploy
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  deploy:
    name: Deploy app
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
    - name: checkout
      uses: actions/checkout@v3
      
    - name: flyctl
      uses: superfly/flyctl-actions/setup-flyctl@master
      
    - name: deploy
      run: flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    - name: Notify
      uses: rjstone/discord-webhook-notify@v1
      if: success()
      with:
        severity: info
        details: Deploy Succeeded
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      
        
