name: pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened,synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install  

      #- name: Check style
        #run: npm run eslint

      - name: Start server
        run: |
          npm run start-prod &
          # Run the server in the background using "&" to allow subsequent steps to execute
          sleep 5  # Add a short delay to ensure the server has time to start
          netstat -tuln  # Print out listening ports to check if the server is running
          curl http://localhost:5000  # Test if the server responds
          ps aux | grep node  # Check if the node process is running
          echo "Server started successfully"

      - name: Wait for server to start
        run: sleep 60 # Adjust the delay as needed
          
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          wait-on: http://localhost:5000



#name: pipeline

#on:
#  push:
#    branches:
#      - main

#jobs:
#  simple_deployment_pipeline:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v4
#        with:
#          node-version: '20'
#      - name: Install dependencies 
#        run: npm install  

      #- name: Check style
        #run: npm run eslint

#      - name: e2e tests
#        uses: cypress-io/github-action@v5
#        with:
#          command: npm run test:e2e
#         start: npm run start-prod
#          wait-on: http://localhost:5000

